### ISSUE TITLE
Use IPFS multiaddress instead of blake256 hash for evidence 

### ISSUE THREAD

**Issue by xlc** [polkadot-fellows/Evidences#15]
It is very very hard for UI to link the preimage of the evidence. It has to check each open PR and calculate the hash and check if it matches to the onchain hash.
If we are using IPFS multiaddress, it is a hash, and we can have some bot here to upload the preimage some IPFS service and then the UI can easily identify the preimage and show it.

**Comment by anaelleltd** [comment]
We are currently testing a new procedure for submitting evidences on-chain that uses IPFS via Subsquare, as shown in the step-by-step guide below.
![EvidenceSubmissionSubsquare](https://github.com/polkadot-fellows/Evidences/assets/44770354/43c3f10c-db28-45a2-af99-597bc5782802)

**Comment by anaelleltd** [comment]
Resolved by [PR #24](https://github.com/polkadot-fellows/Evidences/pull/24)
